# Generated by Django 3.2.13 on 2022-06-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidjango', '0002_sensor_datatype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
