# Generated by Django 3.2.13 on 2022-07-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_sensor_svalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='value',
        ),
    ]
