# Generated by Django 3.2.13 on 2022-08-23 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_remove_sensor_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Io',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('config', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='dataType',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='svalue',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='tod',
        ),
        migrations.AddField(
            model_name='sensor',
            name='config',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
