# Generated by Django 3.2.13 on 2022-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_auto_20220823_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelly2_5_RollerValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roller_id', models.CharField(max_length=30)),
                ('roller', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=6)),
                ('energy', models.CharField(max_length=6)),
                ('position', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelly2_5Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30)),
                ('mode', models.CharField(max_length=30)),
                ('relay_1_id', models.CharField(max_length=30)),
                ('relay_2_id', models.CharField(max_length=30)),
                ('roller_id', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelly2_5Relay_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_id', models.CharField(max_length=30)),
                ('appliance', models.CharField(max_length=30)),
                ('appliance_id', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelly2_5RelayValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_id', models.CharField(max_length=30)),
                ('longpush', models.CharField(max_length=4)),
                ('input_event', models.CharField(max_length=10)),
                ('relay', models.CharField(max_length=4)),
                ('power', models.CharField(max_length=6)),
                ('energy', models.CharField(max_length=6)),
                ('overpower_value', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelly2_5Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30)),
                ('input_0', models.CharField(max_length=4)),
                ('input_1', models.CharField(max_length=4)),
                ('temperature', models.CharField(max_length=5)),
                ('overtemperature', models.CharField(max_length=10)),
                ('temperature_status', models.CharField(max_length=10)),
                ('voltage', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShellyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30)),
                ('device_name', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('device_type', models.CharField(max_length=30)),
                ('firmware_version', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=20)),
                ('mqqt_id', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
