# Generated by Django 3.2.13 on 2022-10-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_alter_shellyconfig_mqqt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shellyconfig',
            old_name='mqqt_id',
            new_name='mqtt_id',
        ),
    ]
